### ISSUE TITLE
version `0.0.1`

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/eo-rs#18]

**Comment by zoeself** [comment]
@h1alexbel thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by h1alexbel** [comment]
@zoeself sdf

**Comment by zoeself** [comment]
> @zoeself sdf

@h1alexbel didn't understand that, sorry.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.1`

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
